version: '3.1'

services:
  postgres:
    container_name: promise-t-postgres
    image: postgres:15
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: promise_t

  redis:
    container_name: promise-t-redis
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres-data:
    driver: local