spring:
  application:
    name: promise_t

  data:
    web:
      pageable:
        one-indexed-parameters: true

topic:
  course-time:
    reserved:
      topic: course-time-reserved
      status-group: course-time-reserved-status-group